# Generated by Django 4.1 on 2022-09-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_theme',
            field=models.CharField(default='light', max_length=255),
        ),
    ]
