# Generated by Django 4.1 on 2022-09-08 11:10

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0002_rename_password_password_old_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='additional_info',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, default='')),
        ),
        migrations.AddField(
            model_name='password',
            name='email',
            field=django_cryptography.fields.encrypt(models.EmailField(blank=True, default='', max_length=255)),
        ),
        migrations.AddField(
            model_name='password',
            name='password',
            field=django_cryptography.fields.encrypt(models.CharField(default='', max_length=255)),
        ),
        migrations.AddField(
            model_name='password',
            name='service',
            field=django_cryptography.fields.encrypt(models.CharField(default='', max_length=255)),
        ),
        migrations.AddField(
            model_name='password',
            name='username',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=255)),
        ),
    ]
