# Generated by Django 4.1 on 2022-09-10 07:53

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0005_remove_password_old_additional_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='service',
        ),
        migrations.AddField(
            model_name='password',
            name='service_icon_url',
            field=models.URLField(default='https://w7.pngwing.com/pngs/285/477/png-transparent-web-development-web-design-internet-web-hosting-service-world-wide-web-logo-symmetry-sphere.png', max_length=255),
        ),
        migrations.AddField(
            model_name='password',
            name='service_url',
            field=django_cryptography.fields.encrypt(models.URLField(default='', max_length=255)),
        ),
    ]
