# Generated by Django 4.1 on 2022-09-10 08:36

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0006_remove_password_service_password_service_icon_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='service_name',
            field=django_cryptography.fields.encrypt(models.CharField(default='', max_length=255)),
        ),
    ]
