# Generated by Django 4.1 on 2022-09-11 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0007_password_service_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='service_icon_url',
            new_name='old_service_icon_url',
        ),
    ]
