# Generated by Django 4.1 on 2022-10-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0011_remove_password_old_service_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='additional_info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='password',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='password',
            name='service_icon_url',
            field=models.URLField(default='https://w7.pngwing.com/pngs/285/477/png-transparent-web-development-web-design-internet-web-hosting-service-world-wide-web-logo-symmetry-sphere.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='password',
            name='service_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='password',
            name='service_url',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='password',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
